-- Расширение для эффективного ILIKE '%...%' по name
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- Домен contract_kind
DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM pg_type t
            JOIN pg_namespace n ON n.oid = t.typnamespace
            WHERE t.typname = 'contract_kind'
              AND n.nspname = 'rightsflow'  -- если домен в схеме public
        ) THEN
            CREATE DOMAIN contract_kind AS CHARACTER(1)
                CHECK (VALUE IN ('S', 'P'));
        END IF;
    END$$;

-- LOV_CONTRACT_TYPE
CREATE TABLE IF NOT EXISTS LOV_CONTRACT_TYPE (
    ID   INTEGER PRIMARY KEY,
    NAME VARCHAR(255) UNIQUE NOT NULL,
    DEF BOOLEAN DEFAULT FALSE
);
COMMENT ON TABLE LOV_CONTRACT_TYPE IS 'Типы контрактов';

-- LOV_CONTRACT_STATUS
CREATE TABLE IF NOT EXISTS LOV_CONTRACT_STATUS (
    ID INTEGER PRIMARY KEY,
    ID_CONTRACT_TYPE INTEGER NOT NULL REFERENCES LOV_CONTRACT_TYPE(ID),
    NAME VARCHAR(255) NOT NULL,
    DEF BOOLEAN DEFAULT FALSE
);
COMMENT ON TABLE LOV_CONTRACT_STATUS IS 'Статусы контрактов';

CREATE INDEX IF NOT EXISTS idx_lov_contract_status ON LOV_CONTRACT_STATUS(ID_CONTRACT_TYPE);

INSERT INTO LOV_CONTRACT_TYPE (ID, NAME, DEF)
VALUES (1,'Сделка','1'::BOOLEAN)
ON CONFLICT (ID) DO NOTHING;
INSERT INTO LOV_CONTRACT_TYPE (ID, NAME, DEF)
VALUES (2,'Договор','0'::BOOLEAN)
ON CONFLICT (ID) DO NOTHING;

INSERT INTO LOV_CONTRACT_STATUS (ID, NAME, ID_CONTRACT_TYPE, DEF)
VALUES (1,'Черновик',1,'1'::BOOLEAN)
ON CONFLICT (ID) DO NOTHING;
INSERT INTO LOV_CONTRACT_STATUS (ID, NAME, ID_CONTRACT_TYPE, DEF)
VALUES (2,'Подписана',1,'0'::BOOLEAN)
ON CONFLICT (ID) DO NOTHING;

INSERT INTO LOV_CONTRACT_STATUS (ID, NAME, ID_CONTRACT_TYPE, DEF)
VALUES (10,'Черновик',2,'1'::BOOLEAN)
ON CONFLICT (ID) DO NOTHING;
INSERT INTO LOV_CONTRACT_STATUS (ID, NAME, ID_CONTRACT_TYPE, DEF)
VALUES (11,'Подписан',2,'0'::BOOLEAN)
ON CONFLICT (ID) DO NOTHING;

-- KLF_COUNTERPARTY
CREATE TABLE IF NOT EXISTS SYNC__KLF_COUNTERPARTY (
    ID          INTEGER PRIMARY KEY,
    GUID        VARCHAR(255) UNIQUE,
    NAME        VARCHAR(255) NOT NULL,
    CREATED_BY  VARCHAR(20)  NOT NULL,
    CREATED_AT  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY  VARCHAR(20),
    UPDATED_AT  TIMESTAMPTZ
);
COMMENT ON TABLE SYNC__KLF_COUNTERPARTY IS 'Контрагенты';

-- KLF_ORGANIZATION
CREATE TABLE IF NOT EXISTS SYNC__KLF_ORGANIZATION (
    ID          INTEGER PRIMARY KEY,
    GUID        VARCHAR(255) UNIQUE,
    NAME        VARCHAR(255) NOT NULL,
    CREATED_BY  VARCHAR(20)  NOT NULL,
    CREATED_AT  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY  VARCHAR(20),
    UPDATED_AT  TIMESTAMPTZ
);
COMMENT ON TABLE SYNC__KLF_ORGANIZATION IS 'Организации';

CREATE INDEX IF NOT EXISTS idx_klf_cpart_guid ON SYNC__KLF_COUNTERPARTY(GUID);
CREATE INDEX IF NOT EXISTS idx_klf_cpart_name_trgm  ON SYNC__KLF_COUNTERPARTY USING gin (NAME gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_klf_org_guid ON SYNC__KLF_ORGANIZATION(GUID);
CREATE INDEX IF NOT EXISTS idx_klf_org_name_trgm  ON SYNC__KLF_ORGANIZATION USING gin (NAME gin_trgm_ops);

-- CONTRACT
CREATE TABLE IF NOT EXISTS CONTRACT (
	ID BIGSERIAL NOT NULL PRIMARY KEY,
    GUID VARCHAR(255) UNIQUE,
    NUM VARCHAR(255) NOT NULL,
    ID_ORG INTEGER NOT NULL REFERENCES SYNC__KLF_ORGANIZATION(ID),
    VALIDITY_PERIOD DATERANGE NOT NULL DEFAULT '(,)'::daterange,
    SIGN_DATE DATE,
    ID_CONTRACT_TYPE INTEGER NOT NULL REFERENCES LOV_CONTRACT_TYPE(ID),
    ID_CONTRACT_STATUS INTEGER NOT NULL REFERENCES LOV_CONTRACT_STATUS(ID),
    IN_OUT CONTRACT_KIND NOT NULL,
    DESCRIPTION VARCHAR(511),
    CREATED_BY VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(20),
    UPDATED_AT TIMESTAMPTZ
);
COMMENT ON TABLE CONTRACT IS 'Контракты';

CREATE INDEX IF NOT EXISTS idx_contract_guid ON CONTRACT(GUID);
CREATE INDEX IF NOT EXISTS idx_contract_num_trgm ON CONTRACT USING gin (NUM gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_contract_org ON CONTRACT(ID_ORG);
CREATE INDEX IF NOT EXISTS idx_contract_type ON CONTRACT(ID_CONTRACT_TYPE);
CREATE INDEX IF NOT EXISTS idx_contract_status ON CONTRACT(ID_CONTRACT_STATUS);
CREATE INDEX IF NOT EXISTS idx_contract_in_out ON CONTRACT(IN_OUT);

-- CONTRACT_COUNTERPARTY
CREATE TABLE IF NOT EXISTS CONTRACT_COUNTERPARTY (
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    ID_CONTRACT BIGINT NOT NULL REFERENCES CONTRACT(ID) ON DELETE CASCADE,
    ID_CPART INTEGER NOT NULL REFERENCES SYNC__KLF_COUNTERPARTY(ID) ON DELETE CASCADE,
    CREATED_BY VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(20),
    UPDATED_AT TIMESTAMPTZ
);
COMMENT ON TABLE CONTRACT_COUNTERPARTY IS 'Контрагенты контракта';

CREATE UNIQUE INDEX IF NOT EXISTS UNQ_CONTRACT_CPART ON CONTRACT_COUNTERPARTY(ID_CONTRACT, ID_CPART);
CREATE INDEX IF NOT EXISTS idx_contract_cpart_contract ON CONTRACT_COUNTERPARTY(ID_CONTRACT);
CREATE INDEX IF NOT EXISTS idx_contract_cpart_cpart ON CONTRACT_COUNTERPARTY(ID_CPART);

-- LOV_OIP_SUPER_TYPE
CREATE TABLE IF NOT EXISTS SYNC__LOV_OIP_SUPER_TYPE (
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR(255) UNIQUE NOT NULL
);
COMMENT ON TABLE SYNC__LOV_OIP_SUPER_TYPE IS 'Виды ОИС';

-- LOV_OIP_TYPE
CREATE TABLE IF NOT EXISTS SYNC__LOV_OIP_TYPE (
    ID INTEGER PRIMARY KEY,
    ID_OIP_SUPER_TYPE INTEGER NOT NULL REFERENCES SYNC__LOV_OIP_SUPER_TYPE(ID),
    NAME VARCHAR(255) NOT NULL
);
COMMENT ON TABLE SYNC__LOV_OIP_TYPE IS 'Типы ОИС';

CREATE UNIQUE INDEX IF NOT EXISTS UNQ_LOV_OIP_TYPE ON SYNC__LOV_OIP_TYPE(ID_OIP_SUPER_TYPE, NAME);

-- KLF_OIP
CREATE TABLE IF NOT EXISTS SYNC__KLF_OIP (
    ID                INTEGER PRIMARY KEY,
    GUID              VARCHAR(255) UNIQUE,
    ID_OIP_SUPER_TYPE INTEGER NOT NULL REFERENCES SYNC__LOV_OIP_SUPER_TYPE(ID),
    ID_OIP_TYPE       INTEGER NOT NULL REFERENCES SYNC__LOV_OIP_TYPE(ID),
    NAME              VARCHAR(512) NOT NULL,
    PART_NUM          INTEGER NOT NULL DEFAULT 0,
    PART_COUNT        INTEGER NOT NULL DEFAULT 0,
    DURATION          INTERVAL,
    CREATED_BY        VARCHAR(20)  NOT NULL,
    CREATED_AT        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY        VARCHAR(20),
    UPDATED_AT        TIMESTAMPTZ
);
COMMENT ON TABLE SYNC__KLF_OIP IS 'ОИС';

CREATE INDEX IF NOT EXISTS idx_klf_oip_super_type ON SYNC__KLF_OIP(ID_OIP_SUPER_TYPE);
CREATE INDEX IF NOT EXISTS idx_klf_oip_type       ON SYNC__KLF_OIP(ID_OIP_TYPE);
CREATE INDEX IF NOT EXISTS idx_klf_oip_name_trgm  ON SYNC__KLF_OIP USING gin (NAME gin_trgm_ops);

-- LOV_CURRENCY
CREATE TABLE IF NOT EXISTS LOV_CURRENCY (
    ID INTEGER PRIMARY KEY,
    ISO_CHAR_CODE VARCHAR(3) UNIQUE NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DEF BOOLEAN DEFAULT FALSE
);
COMMENT ON TABLE LOV_CURRENCY IS 'Виды валют';

INSERT INTO LOV_CURRENCY (ID, ISO_CHAR_CODE, NAME, DEF)
VALUES (1,'RUB','Российский рубль','1'::BOOLEAN)
ON CONFLICT (ID) DO NOTHING;

INSERT INTO LOV_CURRENCY (ID, ISO_CHAR_CODE, NAME, DEF)
VALUES (2,'USD','Доллар США','0'::BOOLEAN)
ON CONFLICT (ID) DO NOTHING;

INSERT INTO LOV_CURRENCY (ID, ISO_CHAR_CODE, NAME, DEF)
VALUES (3,'EUR','Евро','0'::BOOLEAN)
ON CONFLICT (ID) DO NOTHING;

INSERT INTO LOV_CURRENCY (ID, ISO_CHAR_CODE, NAME, DEF)
VALUES (4,'YUE','Китайский юань','0'::BOOLEAN)
ON CONFLICT (ID) DO NOTHING;

-- LICENSE_FORMAT
CREATE TABLE IF NOT EXISTS LICENSE_FORMAT (
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(511),
    CREATED_BY VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(20),
    UPDATED_AT TIMESTAMPTZ
);
COMMENT ON TABLE LICENSE_FORMAT IS 'Формат лицензирования';

-- LICENSE
CREATE TABLE IF NOT EXISTS LICENSE (
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    ID_CONTRACT BIGINT NOT NULL REFERENCES CONTRACT(ID),
    ID_LIC_FORMAT BIGINT REFERENCES LICENSE_FORMAT(ID),
    GUID VARCHAR(255) UNIQUE,
    NUM VARCHAR(255) NOT NULL,
    PRICE DECIMAL NOT NULL DEFAULT 0.0,
    ID_CURRENCY INTEGER NOT NULL REFERENCES LOV_CURRENCY(ID),
    VALIDITY_PERIOD DATERANGE NOT NULL DEFAULT '(,)'::daterange,
    DESCRIPTION VARCHAR(511),
    CREATED_BY VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(20),
    UPDATED_AT TIMESTAMPTZ
);
COMMENT ON TABLE LICENSE IS 'Лицензии';

CREATE INDEX IF NOT EXISTS idx_lic_guid ON LICENSE(GUID);
CREATE INDEX IF NOT EXISTS idx_lic_num_trgm ON LICENSE USING gin (NUM gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_lic_contract ON LICENSE(ID_CONTRACT);
CREATE INDEX IF NOT EXISTS idx_lic_fmt ON LICENSE(ID_LIC_FORMAT);
CREATE INDEX IF NOT EXISTS idx_lic_currency ON LICENSE(ID_CURRENCY);

-- LICENSE_OIP
CREATE TABLE IF NOT EXISTS LICENSE_OIP (
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    ID_LICENSE BIGINT NOT NULL REFERENCES LICENSE(ID) ON DELETE CASCADE,
    ID_OIP INTEGER NOT NULL REFERENCES SYNC__KLF_OIP(ID) ON DELETE CASCADE,
    CREATED_BY VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(20),
    UPDATED_AT TIMESTAMPTZ
);
COMMENT ON TABLE LICENSE_OIP IS 'ОИС в составе лицензии';

CREATE UNIQUE INDEX IF NOT EXISTS UNQ_LICENSE_OIP ON LICENSE_OIP(ID_LICENSE, ID_OIP);
CREATE INDEX IF NOT EXISTS idx_lic_oip_lic ON LICENSE_OIP(ID_LICENSE);
CREATE INDEX IF NOT EXISTS idx_lic_oip_oip ON LICENSE_OIP(ID_OIP);

-- KLF_RIGHT_TYPE
CREATE TABLE IF NOT EXISTS SYNC__KLF_RIGHT_TYPE (
    ID          INTEGER PRIMARY KEY,
    ID_PARENT   INTEGER NULL REFERENCES SYNC__KLF_RIGHT_TYPE(ID) ON DELETE RESTRICT,
    NAME        VARCHAR(255) NOT NULL,
    CREATED_BY  VARCHAR(20)  NOT NULL,
    CREATED_AT  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    UPDATED_BY  VARCHAR(20),
    UPDATED_AT  TIMESTAMPTZ
);
COMMENT ON TABLE SYNC__KLF_RIGHT_TYPE IS 'Типы прав';

CREATE INDEX IF NOT EXISTS IDX_KLF_RIGHT_TYPE_PARENT ON SYNC__KLF_RIGHT_TYPE(ID_PARENT);
CREATE INDEX IF NOT EXISTS IDX_KLF_RIGHT_TYPE_NAME ON SYNC__KLF_RIGHT_TYPE(NAME);

-- LICENSE_RT
CREATE TABLE IF NOT EXISTS LICENSE_RT (
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    ID_LICENSE BIGINT NOT NULL REFERENCES LICENSE(ID),
    ID_RIGHT_TYPE INTEGER NOT NULL REFERENCES SYNC__KLF_RIGHT_TYPE(ID),
    HB_START_DATE DATE,
    HB_DAYS INTEGER,
    CREATED_BY VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(20),
    UPDATED_AT TIMESTAMPTZ
);
COMMENT ON TABLE LICENSE_RT IS 'Привязка типов прав к лицензии';
COMMENT ON COLUMN LICENSE_RT.HB_START_DATE IS 'Дата начала действия holdback-а';
COMMENT ON COLUMN LICENSE_RT.HB_DAYS IS 'Количество дней действия holdback-а';

CREATE UNIQUE INDEX IF NOT EXISTS UNQ_LICENSE_RT ON LICENSE_RT(ID_LICENSE, ID_RIGHT_TYPE);
CREATE INDEX IF NOT EXISTS idx_lic_rt_lic ON LICENSE_RT(ID_LICENSE);
CREATE INDEX IF NOT EXISTS idx_lic_rt_right_type ON LICENSE_RT(ID_RIGHT_TYPE);

-- FORMAT_RT
CREATE TABLE IF NOT EXISTS FORMAT_RT (
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    ID_LIC_FORMAT BIGINT NOT NULL REFERENCES LICENSE_FORMAT(ID),
    ID_RIGHT_TYPE INTEGER NOT NULL REFERENCES SYNC__KLF_RIGHT_TYPE(ID),
    CREATED_BY VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(20),
    UPDATED_AT TIMESTAMPTZ
);
COMMENT ON TABLE FORMAT_RT IS 'Привязка типов прав к формату лицензии';

CREATE UNIQUE INDEX IF NOT EXISTS UNQ_FORMAT_RT ON FORMAT_RT(ID_LIC_FORMAT, ID_RIGHT_TYPE);
CREATE INDEX IF NOT EXISTS idx_fmt_rt_fmt ON FORMAT_RT(ID_LIC_FORMAT);
CREATE INDEX IF NOT EXISTS idx_fmt_rt_right_type ON FORMAT_RT(ID_RIGHT_TYPE);

-- LICENSE_RT_FEATURE_SET
CREATE TABLE IF NOT EXISTS LICENSE_RT_FEATURE_SET (
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    ID_LIC_RT BIGINT NOT NULL REFERENCES LICENSE_RT(ID),
    IS_EXCLUSIVE BOOLEAN NOT NULL DEFAULT FALSE,
    IS_USE_RIGHT BOOLEAN NOT NULL DEFAULT FALSE,
    VALIDITY_PERIOD DATERANGE NOT NULL DEFAULT '(,)'::daterange,
    CREATED_BY VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(20),
    UPDATED_AT TIMESTAMPTZ
);
COMMENT ON TABLE LICENSE_RT_FEATURE_SET IS 'Набор характеристик права';
COMMENT ON COLUMN LICENSE_RT_FEATURE_SET.IS_USE_RIGHT IS 'Признак использования права при эксклюзивной продаже';
COMMENT ON COLUMN LICENSE_RT_FEATURE_SET.IS_EXCLUSIVE IS 'Признак исключительности права';
COMMENT ON COLUMN LICENSE_RT_FEATURE_SET.VALIDITY_PERIOD IS 'Период действия набора характеристик';

CREATE INDEX IF NOT EXISTS idx_lic_rt_ftr_set_lic_rt ON LICENSE_RT_FEATURE_SET(ID_LIC_RT);
CREATE INDEX IF NOT EXISTS idx_lic_rt_ftr_set_exclusive ON LICENSE_RT_FEATURE_SET(IS_EXCLUSIVE);
CREATE INDEX IF NOT EXISTS idx_lic_rt_ftr_set_use_right ON LICENSE_RT_FEATURE_SET(IS_USE_RIGHT);

-- LICENSE_RT_FEATURE_SET_EXT
CREATE TABLE IF NOT EXISTS LICENSE_RT_FEATURE_SET_EXT (
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    ID_FEATURE_SET BIGINT NOT NULL REFERENCES LICENSE_RT_FEATURE_SET(ID) ON DELETE CASCADE,
    ID_LIC_RT BIGINT REFERENCES LICENSE_RT(ID),
    IS_EXCLUSIVE BOOLEAN NOT NULL DEFAULT FALSE,
    IS_USE_RIGHT BOOLEAN NOT NULL DEFAULT FALSE,
    VALIDITY_PERIOD DATERANGE NOT NULL DEFAULT '(,)'::daterange,
    CREATED_BY VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(20),
    UPDATED_AT TIMESTAMPTZ
);
COMMENT ON TABLE LICENSE_RT_FEATURE_SET_EXT IS 'Подготовленный набор характеристик права';

CREATE INDEX IF NOT EXISTS idx_lic_rt_ftr_set_ext_lic_rt ON LICENSE_RT_FEATURE_SET_EXT(ID_LIC_RT);
CREATE INDEX IF NOT EXISTS idx_lic_rt_ftr_set_ext_exclusive ON LICENSE_RT_FEATURE_SET_EXT(IS_EXCLUSIVE);
CREATE INDEX IF NOT EXISTS idx_lic_rt_ftr_set_ext_use_right ON LICENSE_RT_FEATURE_SET_EXT(IS_USE_RIGHT);
CREATE INDEX IF NOT EXISTS idx_lic_rt_ftr_set_ext_ftr_set ON LICENSE_RT_FEATURE_SET_EXT(ID_FEATURE_SET);

-- FORMAT_RT_FEATURE_SET
CREATE TABLE IF NOT EXISTS FORMAT_RT_FEATURE_SET (
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    ID_FMT_RT BIGINT NOT NULL REFERENCES FORMAT_RT(ID),
    IS_EXCLUSIVE BOOLEAN NOT NULL DEFAULT FALSE,
    IS_USE_RIGHT BOOLEAN NOT NULL DEFAULT FALSE,
    VALIDITY_PERIOD DATERANGE NOT NULL DEFAULT '(,)'::daterange,
    CREATED_BY VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(20),
    UPDATED_AT TIMESTAMPTZ
);
COMMENT ON TABLE FORMAT_RT_FEATURE_SET IS 'Набор характеристик права для формата лицензии';
COMMENT ON COLUMN FORMAT_RT_FEATURE_SET.IS_USE_RIGHT IS 'Признак использования права при эксклюзивной продаже';
COMMENT ON COLUMN FORMAT_RT_FEATURE_SET.IS_EXCLUSIVE IS 'Признак исключительности права';
COMMENT ON COLUMN FORMAT_RT_FEATURE_SET.VALIDITY_PERIOD IS 'Период действия набора характеристик';

CREATE INDEX IF NOT EXISTS idx_fmt_rt_ftr_set_fmt_rt ON FORMAT_RT_FEATURE_SET(ID_FMT_RT);
CREATE INDEX IF NOT EXISTS idx_fmt_rt_ftr_set_exclusive ON FORMAT_RT_FEATURE_SET(IS_EXCLUSIVE);
CREATE INDEX IF NOT EXISTS idx_fmt_rt_ftr_set_use_right ON FORMAT_RT_FEATURE_SET(IS_USE_RIGHT);

-- Категории характеристик
CREATE TABLE IF NOT EXISTS SYNC__KLF_FEATURE_CATEGORY (
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    CREATED_BY VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(20),
    UPDATED_AT TIMESTAMPTZ
);
COMMENT ON TABLE SYNC__KLF_FEATURE_CATEGORY IS 'Категории характеристик';

-- Простые характеристики
CREATE TABLE IF NOT EXISTS SYNC__KLF_FEATURE_PLAIN (
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    ID_FEATURE_CATEGORY INTEGER NOT NULL,
    CREATED_BY VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(20),
    UPDATED_AT TIMESTAMPTZ,
    CONSTRAINT FK_KLF_FEATURE_PLAIN_CATEGORY FOREIGN KEY (ID_FEATURE_CATEGORY)
     REFERENCES SYNC__KLF_FEATURE_CATEGORY(ID)
);
COMMENT ON TABLE SYNC__KLF_FEATURE_PLAIN IS 'Простые характеристики';

CREATE INDEX IF NOT EXISTS idx_ftr_plain_cat ON SYNC__KLF_FEATURE_PLAIN(ID_FEATURE_CATEGORY);

-- Дерево характеристик
CREATE TABLE IF NOT EXISTS SYNC__KLF_FEATURE_TREE (
    ID INTEGER PRIMARY KEY,
    ID_PARENT INTEGER,
    ID_FEATURE_CATEGORY INTEGER NOT NULL,
    ID_FEATURE_PLAIN INTEGER NOT NULL,
    VALIDITY_PERIOD DATERANGE NOT NULL DEFAULT '(,)'::DATERANGE,
    CREATED_BY VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(20),
    UPDATED_AT TIMESTAMPTZ,
    CONSTRAINT FK_KLF_FEATURE_TREE_PARENT FOREIGN KEY (ID_PARENT)
        REFERENCES SYNC__KLF_FEATURE_TREE(ID),
    CONSTRAINT FK_KLF_FEATURE_TREE_CATEGORY FOREIGN KEY (ID_FEATURE_CATEGORY)
        REFERENCES SYNC__KLF_FEATURE_CATEGORY(ID),
    CONSTRAINT FK_KLF_FEATURE_TREE_PLAIN FOREIGN KEY (ID_FEATURE_PLAIN)
        REFERENCES SYNC__KLF_FEATURE_PLAIN(ID)
);
COMMENT ON TABLE SYNC__KLF_FEATURE_TREE IS 'Дерево характеристик';

CREATE INDEX IF NOT EXISTS idx_ftr_tree_parent ON SYNC__KLF_FEATURE_TREE(ID_PARENT);
CREATE INDEX IF NOT EXISTS idx_ftr_tree_cat ON SYNC__KLF_FEATURE_TREE(ID_FEATURE_CATEGORY);
CREATE INDEX IF NOT EXISTS idx_ftr_tree_plain ON SYNC__KLF_FEATURE_TREE(ID_FEATURE_PLAIN);

-- LICENSE_RT_FEATURES
CREATE TABLE IF NOT EXISTS LICENSE_RT_FEATURES (
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    ID_LIC_RT BIGINT NOT NULL REFERENCES LICENSE_RT(ID),
    ID_FEATURE_SET BIGINT NOT NULL REFERENCES LICENSE_RT_FEATURE_SET(ID),
    ID_FEATURE_CATEGORY INTEGER NOT NULL REFERENCES SYNC__KLF_FEATURE_CATEGORY(ID),
    ID_FEATURE INTEGER NOT NULL REFERENCES SYNC__KLF_FEATURE_TREE(ID),
    IS_INCLUDED BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_BY VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(20),
    UPDATED_AT TIMESTAMPTZ
);
COMMENT ON TABLE LICENSE_RT_FEATURES IS 'Характеристики набора характеристик';

CREATE INDEX IF NOT EXISTS idx_lic_rt_ftr_lic_rt ON LICENSE_RT_FEATURES(ID_LIC_RT);
CREATE INDEX IF NOT EXISTS idx_lic_rt_ftr_lic_rt_ftr_set ON LICENSE_RT_FEATURES(ID_FEATURE_SET);
CREATE INDEX IF NOT EXISTS idx_lic_rt_ftr_ftr_cat ON LICENSE_RT_FEATURES(ID_FEATURE_CATEGORY);
CREATE INDEX IF NOT EXISTS idx_lic_rt_ftr_ftr ON LICENSE_RT_FEATURES(ID_FEATURE);

-- FORMAT_RT_FEATURES
CREATE TABLE IF NOT EXISTS FORMAT_RT_FEATURES (
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    ID_FMT_RT BIGINT NOT NULL REFERENCES FORMAT_RT(ID),
    ID_FEATURE_SET BIGINT NOT NULL REFERENCES FORMAT_RT_FEATURE_SET(ID),
    ID_FEATURE_CATEGORY INTEGER NOT NULL REFERENCES SYNC__KLF_FEATURE_CATEGORY(ID),
    ID_FEATURE INTEGER NOT NULL REFERENCES SYNC__KLF_FEATURE_TREE(ID),
    IS_INCLUDED BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_BY VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(20),
    UPDATED_AT TIMESTAMPTZ
);
COMMENT ON TABLE FORMAT_RT_FEATURES IS 'Характеристики набора характеристик формата';

CREATE INDEX IF NOT EXISTS idx_fmt_rt_ftr_fmt_rt ON FORMAT_RT_FEATURES(ID_FMT_RT);
CREATE INDEX IF NOT EXISTS idx_fmt_rt_ftr_lic_rt_ftr_set ON FORMAT_RT_FEATURES(ID_FEATURE_SET);
CREATE INDEX IF NOT EXISTS idx_fmt_rt_ftr_ftr_cat ON FORMAT_RT_FEATURES(ID_FEATURE_CATEGORY);
CREATE INDEX IF NOT EXISTS idx_fmt_rt_ftr_ftr ON FORMAT_RT_FEATURES(ID_FEATURE);

-- LICENCE_RT_FEATURES_HASH
CREATE TABLE IF NOT EXISTS LICENSE_RT_FEATURES_HASH (
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    ID_LIC_RT BIGINT NOT NULL REFERENCES LICENSE_RT(ID),
    ID_FEATURE_SET BIGINT NOT NULL REFERENCES LICENSE_RT_FEATURE_SET(ID),
    ID_RIGHT_TYPE INTEGER NOT NULL REFERENCES SYNC__KLF_RIGHT_TYPE(ID),
    HASH_VALUE VARCHAR(1023) NOT NULL,
    CREATED_BY VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(20),
    UPDATED_AT TIMESTAMPTZ
);
COMMENT ON TABLE LICENSE_RT_FEATURES_HASH IS 'Хэш набора характеристик';

CREATE INDEX IF NOT EXISTS idx_lic_rt_ftr_hash_lic_rt ON LICENSE_RT_FEATURES_HASH(ID_LIC_RT);
CREATE INDEX IF NOT EXISTS idx_lic_rt_ftr_hash_lic_rt_ftr_set ON LICENSE_RT_FEATURES_HASH(ID_FEATURE_SET);
CREATE INDEX IF NOT EXISTS idx_lic_rt_ftr_hash_right_type ON LICENSE_RT_FEATURES_HASH(ID_RIGHT_TYPE);

-- FORMAT_RT_FEATURES_HASH
CREATE TABLE IF NOT EXISTS FORMAT_RT_FEATURES_HASH (
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    ID_FMT_RT BIGINT NOT NULL REFERENCES FORMAT_RT(ID),
    ID_FEATURE_SET BIGINT NOT NULL REFERENCES FORMAT_RT_FEATURE_SET(ID),
    ID_RIGHT_TYPE INTEGER NOT NULL REFERENCES SYNC__KLF_RIGHT_TYPE(ID),
    HASH_VALUE VARCHAR(1023) NOT NULL,
    CREATED_BY VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(20),
    UPDATED_AT TIMESTAMPTZ
);
COMMENT ON TABLE FORMAT_RT_FEATURES_HASH IS 'Хэш набора характеристик формата';

CREATE INDEX IF NOT EXISTS idx_fmt_rt_ftr_hash_fmt_rt ON FORMAT_RT_FEATURES_HASH(ID_FMT_RT);
CREATE INDEX IF NOT EXISTS idx_fmt_rt_ftr_hash_fmt_rt_ftr_set ON FORMAT_RT_FEATURES_HASH(ID_FEATURE_SET);
CREATE INDEX IF NOT EXISTS idx_fmt_rt_ftr_hash_right_type ON FORMAT_RT_FEATURES_HASH(ID_RIGHT_TYPE);

-- Пользователи
CREATE TABLE IF NOT EXISTS SYNC__USERS (
    ID INTEGER PRIMARY KEY,
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    DISPLAY_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    ENABLED BOOLEAN DEFAULT TRUE,
    ACCOUNT_NON_EXPIRED BOOLEAN DEFAULT FALSE,
    ACCOUNT_NON_LOCKED BOOLEAN DEFAULT TRUE,
    EXPIRATION_DATE TIMESTAMP,
    LAST_LOGON TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    USER_TYPE VARCHAR(10) NOT NULL DEFAULT 'USER'::CHARACTER VARYING
);
COMMENT ON TABLE SYNC__USERS IS 'Пользователи';

CREATE INDEX IF NOT EXISTS idx_users_username ON SYNC__USERS(USERNAME);
CREATE INDEX IF NOT EXISTS idx_users_email ON SYNC__USERS(EMAIL);
CREATE INDEX IF NOT EXISTS idx_users_enabled ON SYNC__USERS(ENABLED) WHERE ENABLED = TRUE;
CREATE INDEX IF NOT EXISTS idx_users_type_enabled ON SYNC__USERS(USER_TYPE, ENABLED);
CREATE INDEX IF NOT EXISTS idx_users_display_name_trgm ON SYNC__USERS USING gin (DISPLAY_NAME gin_trgm_ops);

-- Создание таблицы управления биндингами (если еще не создана)
CREATE TABLE IF NOT EXISTS KAFKA_BINDINGS_CONTROL (
    ID SERIAL PRIMARY KEY,
    BINDING_NAME VARCHAR(255) UNIQUE NOT NULL,
    BINDING_STATE VARCHAR(10) NOT NULL DEFAULT 'PAUSE'::CHARACTER VARYING,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMPTZ,
    CONSTRAINT CHK_BINDING_STATE CHECK (BINDING_STATE::TEXT = ANY (ARRAY['PAUSE'::CHARACTER VARYING, 'RESUME'::CHARACTER VARYING]::TEXT[]))
);

-- Добавление триггера для автоматического обновления updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
    RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS update_kafka_bindings_control_updated_at ON kafka_bindings_control;
CREATE TRIGGER update_kafka_bindings_control_updated_at
    BEFORE UPDATE ON kafka_bindings_control
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

INSERT INTO KAFKA_BINDINGS_CONTROL (BINDING_NAME, BINDING_STATE)
VALUES
    ('userProcessor-in-0','PAUSE')
ON CONFLICT (BINDING_NAME) DO NOTHING;

INSERT INTO KAFKA_BINDINGS_CONTROL (BINDING_NAME, BINDING_STATE)
VALUES
    ('counterpartyProcessor-in-0','PAUSE')
ON CONFLICT (BINDING_NAME) DO NOTHING;

INSERT INTO KAFKA_BINDINGS_CONTROL (BINDING_NAME, BINDING_STATE)
VALUES
    ('organizationProcessor-in-0','PAUSE')
ON CONFLICT (BINDING_NAME) DO NOTHING;

INSERT INTO KAFKA_BINDINGS_CONTROL (BINDING_NAME, BINDING_STATE)
VALUES
    ('oipProcessor-in-0','PAUSE')
ON CONFLICT (BINDING_NAME) DO NOTHING;

INSERT INTO KAFKA_BINDINGS_CONTROL (BINDING_NAME, BINDING_STATE)
VALUES
    ('oipSuperTypeProcessor-in-0','PAUSE')
ON CONFLICT (BINDING_NAME) DO NOTHING;

INSERT INTO KAFKA_BINDINGS_CONTROL (BINDING_NAME, BINDING_STATE)
VALUES
    ('oipTypeProcessor-in-0','PAUSE')
ON CONFLICT (BINDING_NAME) DO NOTHING;

INSERT INTO KAFKA_BINDINGS_CONTROL (BINDING_NAME, BINDING_STATE)
VALUES
    ('rightTypeProcessor-in-0','PAUSE')
ON CONFLICT (BINDING_NAME) DO NOTHING;

INSERT INTO KAFKA_BINDINGS_CONTROL (BINDING_NAME, BINDING_STATE)
VALUES
    ('featureCategoryProcessor-in-0','PAUSE')
ON CONFLICT (BINDING_NAME) DO NOTHING;

INSERT INTO KAFKA_BINDINGS_CONTROL (BINDING_NAME, BINDING_STATE)
VALUES
    ('featurePlainProcessor-in-0','PAUSE')
ON CONFLICT (BINDING_NAME) DO NOTHING;

INSERT INTO KAFKA_BINDINGS_CONTROL (BINDING_NAME, BINDING_STATE)
VALUES
    ('featureTreeProcessor-in-0','PAUSE')
ON CONFLICT (BINDING_NAME) DO NOTHING;



