-- Создание таблицы для отсутствующих прав
CREATE TABLE IF NOT EXISTS MISSING_RIGHT (
 ID BIGSERIAL PRIMARY KEY,
 ID_ORG INTEGER NOT NULL REFERENCES SYNC__KLF_ORGANIZATION(ID) ON DELETE CASCADE,
 ID_OIP INTEGER NOT NULL REFERENCES SYNC__KLF_OIP(ID) ON DELETE CASCADE,
 ID_CONTRACT BIGINT NOT NULL REFERENCES CONTRACT(ID) ON DELETE CASCADE,
 ID_LICENSE BIGINT NOT NULL REFERENCES LICENSE(ID) ON DELETE CASCADE,
 ID_LIC_RIGHTS BIGINT NOT NULL REFERENCES LICENSE_RIGHTS(ID) ON DELETE CASCADE,
 ID_LIC_RIGHTS_RT BIGINT NOT NULL REFERENCES LICENSE_RIGHTS_RT(ID) ON DELETE CASCADE,
 ID_RIGHT_TYPE INTEGER NOT NULL REFERENCES SYNC__KLF_RIGHT_TYPE ON DELETE CASCADE,
 FEATURES_HASH VARCHAR(255) NOT NULL,
 BEG_DATE DATE NOT NULL,
 END_DATE DATE NOT NULL,
 IS_EXCLUSIVE BOOLEAN NOT NULL,
 RIGHT_KEY VARCHAR(255) NOT NULL,
 MISSING_FLAG INTEGER NOT NULL DEFAULT -1,
 MISSING_RIGHT_INFO TEXT,
 CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UPDATED_AT TIMESTAMPTZ,
 CONSTRAINT CHK_MISSING_FLAG CHECK(MISSING_FLAG = ANY(ARRAY[1,-1]::INTEGER[]))
);

COMMENT ON TABLE MISSING_RIGHT IS 'Таблица отсутствующих прав';
COMMENT ON COLUMN MISSING_RIGHT.MISSING_FLAG IS '1 - право отсутствует, -1 - право проверяется';

CREATE INDEX IF NOT EXISTS IDX_MISSING_RIGHT_ORG ON MISSING_RIGHT(ID_ORG);
CREATE INDEX IF NOT EXISTS IDX_MISSING_RIGHT_OIP ON MISSING_RIGHT(ID_OIP);
CREATE INDEX IF NOT EXISTS IDX_MISSING_RIGHT_CONTRACT ON MISSING_RIGHT(ID_CONTRACT);
CREATE INDEX IF NOT EXISTS IDX_MISSING_RIGHT_LICENSE ON MISSING_RIGHT(ID_LICENSE);
CREATE INDEX IF NOT EXISTS IDX_MISSING_RIGHT_LIC_RIGHTS ON MISSING_RIGHT(ID_LIC_RIGHTS);
CREATE INDEX IF NOT EXISTS IDX_MISSING_RIGHT_LIC_RIGHTS_RT ON MISSING_RIGHT(ID_LIC_RIGHTS_RT);
CREATE INDEX IF NOT EXISTS IDX_MISSING_RIGHT_RT ON MISSING_RIGHT(ID_RIGHT_TYPE);
CREATE INDEX IF NOT EXISTS IDX_MISSING_RIGHT_KEY ON MISSING_RIGHT(RIGHT_KEY);
CREATE INDEX IF NOT EXISTS IDX_MISSING_RIGHT_GKEY ON MISSING_RIGHT(ID_LIC_RIGHTS, RIGHT_KEY);

INSERT INTO KAFKA_BINDINGS_CONTROL (BINDING_NAME, BINDING_STATE)
VALUES
    ('missingRightProcessor-in-0','PAUSE')
ON CONFLICT (BINDING_NAME) DO NOTHING;