-- LOV_OBJECT
CREATE TABLE IF NOT EXISTS SYNC__LOV_OBJECT
(
    ID INTEGER NOT NULL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL UNIQUE,
    TABLE_NAME VARCHAR(100),
    WHERE_FILTER VARCHAR(255),
    ID_SVC INTEGER NOT NULL DEFAULT 0
);
COMMENT ON TABLE SYNC__LOV_OBJECT IS 'Сущностные объекты';

-- LOV_PGE_PROP_TYPE
CREATE TABLE IF NOT EXISTS SYNC__LOV_PGE_PROP_TYPE
(
    ID INTEGER NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) UNIQUE NOT NULL,
    ID_OBJ INTEGER,
    USE_MULTI_SELECT BOOLEAN NOT NULL DEFAULT FALSE
);
COMMENT ON TABLE SYNC__LOV_PGE_PROP_TYPE IS 'Типы свойств';

CREATE INDEX IF NOT EXISTS SYNC__LOV_PT_OBJ_IDX ON SYNC__LOV_PGE_PROP_TYPE(ID_OBJ);

-- LOV_PGE_PROPERTY
CREATE TABLE IF NOT EXISTS SYNC__LOV_PGE_PROPERTY
(
    ID INTEGER NOT NULL PRIMARY KEY,
    CODE VARCHAR(20) NOT NULL UNIQUE,
    NAME VARCHAR(100) UNIQUE NOT NULL,
    ID_PROP_TYPE INTEGER NOT NULL
);
COMMENT ON TABLE SYNC__LOV_PGE_PROPERTY IS 'Свойства';

CREATE INDEX IF NOT EXISTS SYNC__LOV_P_PT_IDX ON SYNC__LOV_PGE_PROPERTY(ID_PROP_TYPE);

-- LOV_PGE_PROPERTY_GROUP
CREATE TABLE IF NOT EXISTS SYNC__LOV_PGE_PROPERTY_GROUP
(
    ID INTEGER NOT NULL PRIMARY KEY,
    CODE VARCHAR(20) NOT NULL UNIQUE,
    NAME VARCHAR(100) NOT NULL,
    LAYER_SEL_QUERY TEXT,
    SVC_ID INTEGER NOT NULL DEFAULT 0
);
COMMENT ON TABLE SYNC__LOV_PGE_PROPERTY_GROUP IS 'Группа свойств';

-- LOV_PGE_PG_LAYER
CREATE TABLE IF NOT EXISTS SYNC__LOV_PGE_PG_LAYER
(
    ID    INTEGER NOT NULL PRIMARY KEY,
    ID_PG INTEGER NOT NULL,
    SEL_VALUE VARCHAR(255) NOT NULL
);
COMMENT ON TABLE SYNC__LOV_PGE_PG_LAYER IS 'Слой группы свойств';

CREATE INDEX IF NOT EXISTS SYNC__LOV_PGL_PG_IDX ON SYNC__LOV_PGE_PG_LAYER(ID_PG);

-- LOV_PGE_PROPERTY_GROUP_DTL
CREATE TABLE IF NOT EXISTS SYNC__LOV_PGE_PGL_DTL
(
    ID INTEGER NOT NULL PRIMARY KEY,
    ID_PGL INTEGER NOT NULL,
    ID_PROPERTY INTEGER NOT NULL,
    PROPERTY_FORMAT VARCHAR(255),
    DEFAULT_VALUE VARCHAR(255),
    PG_ORDER INTEGER DEFAULT 0 NOT NULL
);
COMMENT ON TABLE SYNC__LOV_PGE_PGL_DTL IS 'Состав группы свойств в слое';

DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'sync__lov_pge_prp_grp_dt_uk') THEN
            ALTER TABLE SYNC__LOV_PGE_PGL_DTL
                ADD CONSTRAINT SYNC__LOV_PGE_PRP_GRP_DT_UK UNIQUE(ID_PGL, ID_PROPERTY);
        END IF;
    END $$;

CREATE INDEX IF NOT EXISTS SYNC__LOV_PGL_DTL_PGL_UDX ON SYNC__LOV_PGE_PGL_DTL(ID_PGL);
CREATE INDEX IF NOT EXISTS SYNC__LOV_PGL_DTL_PRP_UDX ON SYNC__LOV_PGE_PGL_DTL(ID_PROPERTY);
CREATE INDEX IF NOT EXISTS SYNC__LOV_PGL_DTL_ORD_UDX ON SYNC__LOV_PGE_PGL_DTL(PG_ORDER);

-- LOV_PROPERTY_GROUP_TO_OBJ
CREATE TABLE IF NOT EXISTS SYNC__LOV_PGE_PG_TO_OBJ
(
    ID INTEGER NOT NULL PRIMARY KEY,
    ID_OBJ INTEGER NOT NULL,
    CODE_PG VARCHAR(20) NOT NULL
);
COMMENT ON TABLE SYNC__LOV_PGE_PG_TO_OBJ IS 'Связь групп свойств с сущностями';

CREATE INDEX IF NOT EXISTS SYNC__LOV_PG_TO_OBJ_OBJ_IDX ON SYNC__LOV_PGE_PG_TO_OBJ(ID_OBJ);
CREATE INDEX IF NOT EXISTS SYNC__LOV_PG_TO_OBJ_CODE_IDX ON SYNC__LOV_PGE_PG_TO_OBJ(CODE_PG);

DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'sync__lov_pg_to_obj_uk') THEN
            ALTER TABLE SYNC__LOV_PGE_PG_TO_OBJ
                ADD CONSTRAINT SYNC__LOV_PG_TO_OBJ_UK UNIQUE(ID_OBJ, CODE_PG);
        END IF;
    END $$;

-- PGE_PROPS
CREATE TABLE IF NOT EXISTS PGE_PROPS
(
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    ID_PGL INTEGER NOT NULL REFERENCES SYNC__LOV_PGE_PG_LAYER(ID),
    ID_PROPERTY INTEGER NOT NULL REFERENCES SYNC__LOV_PGE_PROPERTY(ID),
    ID_ENTITY BIGINT NOT NULL,
    PROPERTY_VALUE VARCHAR(255),
    CREATED_BY  VARCHAR(20)  NOT NULL,
    CREATED_AT  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY  VARCHAR(20),
    UPDATED_AT  TIMESTAMPTZ
);
COMMENT ON TABLE PGE_PROPS IS 'Значения свойств';

DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'pge_props_uk') THEN
            ALTER TABLE PGE_PROPS
                ADD CONSTRAINT PGE_PROPS_UK UNIQUE(ID_PGL, ID_PROPERTY, ID_ENTITY);
        END IF;
    END $$;

CREATE INDEX IF NOT EXISTS PGE_PROPS_PGL_IDX ON PGE_PROPS(ID_PGL);
CREATE INDEX IF NOT EXISTS PGE_PROPS_PRP_IDX ON PGE_PROPS(ID_PROPERTY);
CREATE INDEX IF NOT EXISTS PGE_PROPS_ENT_IDX ON PGE_PROPS(ID_ENTITY);

-- PGE_PROPS_LIC_RIGHTS_RT
CREATE TABLE IF NOT EXISTS PGE_PROPS_LIC_RIGHTS_RT
(
    ID BIGINT NOT NULL PRIMARY KEY,
    ID_LIC_RIGHTS_RT BIGINT NOT NULL REFERENCES LICENSE_RIGHTS_RT(ID)
);
COMMENT ON TABLE PGE_PROPS_LIC_RIGHTS_RT IS 'Связь свойств со способами использования';

CREATE INDEX IF NOT EXISTS PGE_PROPS_RT_RT_IDX ON PGE_PROPS_LIC_RIGHTS_RT(ID_LIC_RIGHTS_RT);


-- Составной индекс для быстрого поиска значений свойств
CREATE INDEX IF NOT EXISTS pge_props_composite_idx
    ON PGE_PROPS(id_pgl, id_property, id_entity)
    INCLUDE (property_value);

-- Индекс для фильтрации по CODE
CREATE INDEX IF NOT EXISTS sync__lov_pge_pg_code_idx
    ON SYNC__LOV_PGE_PROPERTY_GROUP(code)
    INCLUDE (layer_sel_query);

-- Частичный индекс для справочных типов
CREATE INDEX IF NOT EXISTS sync__lov_pge_prop_type_ref_idx
    ON SYNC__LOV_PGE_PROP_TYPE(id_obj)
    WHERE id_obj IS NOT NULL;

-- Управление очередями
INSERT INTO KAFKA_BINDINGS_CONTROL (BINDING_NAME, BINDING_STATE)
VALUES
    ('objectProcessor-in-0','PAUSE')
ON CONFLICT (BINDING_NAME) DO NOTHING;

INSERT INTO KAFKA_BINDINGS_CONTROL (BINDING_NAME, BINDING_STATE)
VALUES
    ('pgePgLayerProcessor-in-0','PAUSE')
ON CONFLICT (BINDING_NAME) DO NOTHING;

INSERT INTO KAFKA_BINDINGS_CONTROL (BINDING_NAME, BINDING_STATE)
VALUES
    ('pgePgToObjProcessor-in-0','PAUSE')
ON CONFLICT (BINDING_NAME) DO NOTHING;

INSERT INTO KAFKA_BINDINGS_CONTROL (BINDING_NAME, BINDING_STATE)
VALUES
    ('pgePglDtlProcessor-in-0','PAUSE')
ON CONFLICT (BINDING_NAME) DO NOTHING;

INSERT INTO KAFKA_BINDINGS_CONTROL (BINDING_NAME, BINDING_STATE)
VALUES
    ('pgePropTypeProcessor-in-0','PAUSE')
ON CONFLICT (BINDING_NAME) DO NOTHING;

INSERT INTO KAFKA_BINDINGS_CONTROL (BINDING_NAME, BINDING_STATE)
VALUES
    ('pgePropertyProcessor-in-0','PAUSE')
ON CONFLICT (BINDING_NAME) DO NOTHING;

INSERT INTO KAFKA_BINDINGS_CONTROL (BINDING_NAME, BINDING_STATE)
VALUES
    ('pgePropertyGroupProcessor-in-0','PAUSE')
ON CONFLICT (BINDING_NAME) DO NOTHING;